### ISSUE TITLE
Bug for WebUI 1.6.0

### ISSUE THREAD

**Issue by RunawayOrange** [pharmapsychotic/clip-interrogator-ext#67]
Loading CLIP Interrogator 0.5.4...
load checkpoint from H:\Stable Diffusion\models\BLIP\model_base_caption_capfilt_large.pth
Loading CLIP model...
Loaded CLIP model and data in 7.43 seconds.
The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 0

**Comment by RexLeeGrey** [comment]
same

**Comment by ostap667inbox** [comment]
Yes. Any model

**Comment by Grocel** [comment]
Duplicate of #64 and #59.

**Comment by pharmapsychotic** [comment]
@RunawayOrange I've update the extension now can you give it a try and confirm is fixed for you.

**Comment by Grocel** [comment]
> @RunawayOrange I've update the extension now can you give it a try and confirm is fixed for you.

I can confirm. This is fixed for me now.

**Comment by Snomov** [comment]
> @RunawayOrange I've update the extension now can you give it a try and confirm is fixed for you.

I updated this from the webui interface, the error remains. When I completely uninstalled this extension and reinstalled it, it worked. Thanks!
